-- Q5:  What is the total revenue generated by each product?

 SELECT 
 p.product_name,
 sum(p.price * o.quantity) AS Total_price
 FROM products AS p
 INNER JOIN orders AS o
 ON p.product_id = o.product_id
 GROUP BY p.product_name
 ORDER BY Total_price DESC;